# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN:
    container_name: ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN/tls/:/var/hyperledger/orderer/tls
        - ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN:/var/hyperledger/production/orderer
    ports:
      - ORDERER_PORT:ORDERER_PORT

  peer0.ORG1_DOMAIN:
    container_name: peer0.ORG1_DOMAIN
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ORG1_DOMAIN
      - CORE_PEER_ADDRESS=peer0.ORG1_DOMAIN:PEER0_ORG1_PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:PEER0_ORG1_PORT
      - CORE_PEER_CHAINCODEADDRESS=peer0.ORG1_DOMAIN:PEER0_ORG1_CC_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:PEER0_ORG1_CC_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ORG1_DOMAIN:PEER1_ORG1_PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ORG1_DOMAIN:PEER0_ORG1_PORT
      - CORE_PEER_LOCALMSPID=ORG1_MSP_NAME
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ORG1_DOMAIN/peers/peer0.ORG1_DOMAIN/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ORG1_DOMAIN/peers/peer0.ORG1_DOMAIN/tls:/etc/hyperledger/fabric/tls
        - peer0.ORG1_DOMAIN:/var/hyperledger/production
    ports:
      - PEER0_ORG1_PORT:PEER0_ORG1_PORT

  peer1.ORG1_DOMAIN:
    container_name: peer1.ORG1_DOMAIN
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ORG1_DOMAIN
      - CORE_PEER_ADDRESS=peer1.ORG1_DOMAIN:PEER1_ORG1_PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:PEER1_ORG1_PORT
      - CORE_PEER_CHAINCODEADDRESS=peer1.ORG1_DOMAIN:PEER1_ORG1_CC_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:PEER1_ORG1_CC_PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ORG1_DOMAIN:PEER1_ORG1_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ORG1_DOMAIN:PEER0_ORG1_PORT
      - CORE_PEER_LOCALMSPID=ORG1_MSP_NAME
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ORG1_DOMAIN/peers/peer1.ORG1_DOMAIN/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ORG1_DOMAIN/peers/peer1.ORG1_DOMAIN/tls:/etc/hyperledger/fabric/tls
        - peer1.ORG1_DOMAIN:/var/hyperledger/production

    ports:
      - PEER1_ORG1_PORT:PEER1_ORG1_PORT

  peer0.ORG2_DOMAIN:
    container_name: peer0.ORG2_DOMAIN
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ORG2_DOMAIN
      - CORE_PEER_ADDRESS=peer0.ORG2_DOMAIN:PEER0_ORG2_PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:PEER0_ORG2_PORT
      - CORE_PEER_CHAINCODEADDRESS=peer0.ORG2_DOMAIN:PEER0_ORG2_CC_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:PEER0_ORG2_CC_PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ORG2_DOMAIN:PEER0_ORG2_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ORG2_DOMAIN:PEER1_ORG2_PORT
      - CORE_PEER_LOCALMSPID=ORG2_MSP_NAME
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ORG2_DOMAIN/peers/peer0.ORG2_DOMAIN/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ORG2_DOMAIN/peers/peer0.ORG2_DOMAIN/tls:/etc/hyperledger/fabric/tls
        - peer0.ORG2_DOMAIN:/var/hyperledger/production
    ports:
      - PEER0_ORG2_PORT:PEER0_ORG2_PORT

  peer1.ORG2_DOMAIN:
    container_name: peer1.ORG2_DOMAIN
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ORG2_DOMAIN
      - CORE_PEER_ADDRESS=peer1.ORG2_DOMAIN:PEER1_ORG2_PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:PEER1_ORG2_PORT
      - CORE_PEER_CHAINCODEADDRESS=peer1.ORG2_DOMAIN:PEER1_ORG2_CC_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:PEER1_ORG2_CC_PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ORG2_DOMAIN:PEER1_ORG2_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ORG2_DOMAIN:PEER0_ORG2_PORT
      - CORE_PEER_LOCALMSPID=ORG2_MSP_NAME
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ORG2_DOMAIN/peers/peer1.ORG2_DOMAIN/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ORG2_DOMAIN/peers/peer1.ORG2_DOMAIN/tls:/etc/hyperledger/fabric/tls
        - peer1.ORG2_DOMAIN:/var/hyperledger/production
    ports:
      - PEER1_ORG2_PORT:PEER1_ORG2_PORT
