# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN:
  ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN:
  ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN:
  ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN:

networks:
  NETWORK_NAME:

services:

  ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN
    networks:
    - NETWORK_NAME
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN/tls/:/var/hyperledger/orderer/tls
        - ORDERER_LOWERCASE_NAME2.ORDERER_DOMAIN:/var/hyperledger/production/orderer
    ports:
    - RAFT2_PORT:ORDERER_PORT

  ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN
    networks:
    - NETWORK_NAME
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN/tls/:/var/hyperledger/orderer/tls
        - ORDERER_LOWERCASE_NAME3.ORDERER_DOMAIN:/var/hyperledger/production/orderer
    ports:
    - RAFT3_PORT:ORDERER_PORT

  ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN
    networks:
    - NETWORK_NAME
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN/tls/:/var/hyperledger/orderer/tls
        - ORDERER_LOWERCASE_NAME4.ORDERER_DOMAIN:/var/hyperledger/production/orderer
    ports:
    - RAFT4_PORT:ORDERER_PORT

  ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN
    networks:
    - NETWORK_NAME
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ORDERER_DOMAIN/orderers/ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN/tls/:/var/hyperledger/orderer/tls
        - ORDERER_LOWERCASE_NAME5.ORDERER_DOMAIN:/var/hyperledger/production/orderer
    ports:
    - RAFT5_PORT:ORDERER_PORT
