# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN:
  peer0.ORG1_DOMAIN:
  peer1.ORG1_DOMAIN:
  peer0.ORG2_DOMAIN:
  peer1.ORG2_DOMAIN:

networks:
  byfn:

services:

  ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN:
    extends:
      file:   base/docker-compose-base.yaml
      service: ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN
    container_name: ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN
    networks:
      - byfn

  peer0.ORG1_DOMAIN:
    container_name: peer0.ORG1_DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ORG1_DOMAIN
    networks:
      - byfn

  peer1.ORG1_DOMAIN:
    container_name: peer1.ORG1_DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ORG1_DOMAIN
    networks:
      - byfn

  peer0.ORG2_DOMAIN:
    container_name: peer0.ORG2_DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ORG2_DOMAIN
    networks:
      - byfn

  peer1.ORG2_DOMAIN:
    container_name: peer1.ORG2_DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ORG2_DOMAIN
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ORG1_DOMAIN:7051
      - CORE_PEER_LOCALMSPID=ORG1_MSP_NAME
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ORG1_DOMAIN/peers/peer0.ORG1_DOMAIN/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ORG1_DOMAIN/peers/peer0.ORG1_DOMAIN/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ORG1_DOMAIN/peers/peer0.ORG1_DOMAIN/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ORG1_DOMAIN/users/Admin@ORG1_DOMAIN/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ORDERER_LOWERCASE_NAME.ORDERER_DOMAIN
      - peer0.ORG1_DOMAIN
      - peer1.ORG1_DOMAIN
      - peer0.ORG2_DOMAIN
      - peer1.ORG2_DOMAIN
    networks:
      - byfn
